### PR TITLE
Implement missing options

### PR DESCRIPTION
**Pull request by joshq00**
Adds all settings available to `cf push`

### CODE REVIEW

**Comment by joshq00** [comment]
@tboerger @bradrydzewski any issues?

**Comment by joshq00** [comment]
After this, I plan to open another PR that adds test coverage for all commands

**Comment by tboerger** [comment]
LGTM until we get a real go sdk implementation :)

**Comment by joshq00** [comment]
I'll be pairing with one of the folks from pivotal on Friday to get started on just that!

**Comment by tboerger** [comment]
I'm merging it now as the code looks fine and nobody else is currently interested in that.

**Pull request merged**
