### PR TITLE
add --route-path args to command

### PR DESCRIPTION
**Pull request by johnverrone**
`--route-path` is not a boolean option, adding the value to the script.

### CODE REVIEW

**Review by cheslip — APPROVED** [review]

**Comment by cheslip** [comment]
Thanks for the contribution @johnverrone - I can merge as soon as the CLA is signed

**Comment by johnverrone** [comment]
Sounds good @cheslip, just working with some officers to get it signed. Thanks!

**Comment by billimek** [comment]
@cheslip we had our officer sign the CLA on behalf of @homedepot via the [cla link](https://cla-assistant.io/Comcast/drone-cloudfoundry?pullRequest=17) - is there an additional step we need to take for this to reflect?

**Comment by cheslip** [comment]
any chance @johnverrone can sign also? The tool looks for the person who opened the PR. If not I'll see what we can do

**Comment by joshq00** [comment]
We had an executive sign on behalf of @homedepot as @billimek mentioned.

@johnverrone will sign but just for the sake of the CLAassistant accepting the PR - only the VP signature is considered valid. @billimek do you agree with this approach?

**Comment by cheslip** [comment]
thanks everyone!

**Pull request merged**
